<html>
    <head>
        głowa
    </head>
    <body>
        <div>kokoko:</div>
        <p>ososos</p>
        <name>KUBA</name>
        <p>sdsdsdsds</p>
    </body>
    <footer>hohos</footer>
</html>